-- constants.lua
-- All game constants in one place

local C = {}

C.WINDOW_WIDTH = 640
C.WINDOW_HEIGHT = 480

C.FIELD_MARGIN = 32

C.PADDLE_WIDTH = 10
C.PADDLE_HEIGHT = 60
C.PADDLE_SPEED = 240
C.PADDLE_INIT_Y = (C.WINDOW_HEIGHT - C.PADDLE_HEIGHT) / 2
C.LEFT_X = C.FIELD_MARGIN
C.RIGHT_X = C.WINDOW_WIDTH - C.FIELD_MARGIN - C.PADDLE_WIDTH

C.PUCK_SIZE = 10
C.PUCK_SPEED = 200

C.MAX_SCORE = 10

C.COLOR_BG = {0, 0, 0}    -- Black
C.COLOR_FG = {1, 1, 1}    -- White

C.DOTTED_SIZE = 10
C.DOTTED_GAP = 10

return C
